name: cashie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  intl: ^0.19.0
  image_picker: ^0.8.7+4
  provider: ^6.0.5
  shared_preferences: ^2.3.2
  material_color_utilities: ^0.11.1
  permission_handler: ^8.3.0
  flutter_sound: ^8.1.9
  flutter_quill: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/items_icon.jpg"


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/items_icon.jpg
    - assets/fonts/

  fonts:
    - family: Nickelodeon
      fonts:
        - asset: assets/fonts/nickelodeon font 2.0 por disney channel nick city.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

