// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyAf_2nfhat-WbV0QtrGhTeTRZeTAXHDk',
    appId: '1:537131346842:web:fe061ec65e46fde44ca823',
    messagingSenderId: '537131346842',
    projectId: 'cashie-101',
    authDomain: 'cashie-101.firebaseapp.com',
    storageBucket: 'cashie-101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQH5n7VZg0gwSe47ukZucWInlzHQ7ds8s',
    appId: '1:537131346842:android:03ff6bd79ebbf36e4ca823',
    messagingSenderId: '537131346842',
    projectId: 'cashie-101',
    storageBucket: 'cashie-101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcRDuWsaRa8pKGcjmhxh_P27HkgLErK-o',
    appId: '1:537131346842:ios:0b3c1d043d4ed9e64ca823',
    messagingSenderId: '537131346842',
    projectId: 'cashie-101',
    storageBucket: 'cashie-101.appspot.com',
    iosBundleId: 'com.example.cashie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcRDuWsaRa8pKGcjmhxh_P27HkgLErK-o',
    appId: '1:537131346842:ios:0b3c1d043d4ed9e64ca823',
    messagingSenderId: '537131346842',
    projectId: 'cashie-101',
    storageBucket: 'cashie-101.appspot.com',
    iosBundleId: 'com.example.cashie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyAf_2nfhat-WbV0QtrGhTeTRZeTAXHDk',
    appId: '1:537131346842:web:2dfb3aea44ba08e54ca823',
    messagingSenderId: '537131346842',
    projectId: 'cashie-101',
    authDomain: 'cashie-101.firebaseapp.com',
    storageBucket: 'cashie-101.appspot.com',
  );
}
